let data = [
    {
        id:1,
        title: "SALOMON",
        sub_title: "KASINA X SALOMON XT-4 OG",
        content: "카시나 X 살로몬 XT-4 OG 다크 네이비",
        product_img: "/img/5.png",
        imgPage: "/img/5.png",
        price: "280000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/5.png"},
            {imgDetail: "/img/5-2.png"},
            {imgDetail: "/img/5-3.png"},
            {imgDetail: "/img/5-4.png"},
            {imgDetail: "/img/5-5.png"},
            {imgDetail: "/img/5-6.png"},
        ],
        itemNumber: "STYLE NO: L47953300",
        color: "COLOR: Dark N/Wht/Haut"
    },
    {
        id:2,
        title: "ON",
        sub_title: "ON Cloudzone 1 M",
        content: "온 클라우드존 1 남성 아이스",
        product_img: "/img/6.png",
        imgPage: "/img/6.png",
        price: "179000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/6.png"},
            {imgDetail: "/img/6-2.png"},
            {imgDetail: "/img/6-3.png"},
            {imgDetail: "/img/6-4.png"},
            {imgDetail: "/img/6-5.png"},
            {imgDetail: "/img/6-6.png"},
        ],
        itemNumber: "STYLE NO: 3MF10081926",
        color: "COLOR: ICE"
    },
    {
        id:3,
        title: "NIKE",
        sub_title: "NIKE AIR FORCE 1 LOW RETRO",
        content: "나이키 에어 포스 1 로우 레트로 이스케이프",
        product_img: "/img/7.png",
        imgPage: "/img/7.png",
        price: "179000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/7.png"},
            {imgDetail: "/img/7-2.png"},
            {imgDetail: "/img/7-3.png"},
            {imgDetail: "/img/7-4.png"},
            {imgDetail: "/img/7-5.png"},
            {imgDetail: "/img/7-6.png"},
        ],
        itemNumber: "STYLE NO: HJ4323-100",
        color: "COLOR: WHITE/BLACK-BISON"
    },
    {
        id:4,
        title: "Polo Ralph Lauren",
        sub_title: "KASINA X POLO RALPH LAUREN TAEGEUK CAPSULE BAYPORT WINDBREAKER",
        content: "카시나 X 폴로 랄프 로렌 태극 캡슐 베이포트 윈드브레이커 네이비",
        product_img: "/img/8.png",
        imgPage: "/img/8.png",
        price: "271200",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/8.png"},
            {imgDetail: "/img/8-2.png"},
            {imgDetail: "/img/8-3.png"},
            {imgDetail: "/img/8-4.png"},
            {imgDetail: "/img/8-5.png"},
            {imgDetail: "/img/8-6.png"},
            {imgDetail: "/img/8-7.png"},
            {imgDetail: "/img/8-8.png"},
            {imgDetail: "/img/8-9.png"},
        ],
        itemNumber: "STYLE NO: MNPOOTW16021595",
        color: "COLOR: NAVY"
    },
    {
        id:5,
        title: "NIKE",
        sub_title: "NIKE WMNS AIR RIFT",
        content: "나이키 우먼스 에어 리프트 레드 세피아",
        product_img: "/img/9.png",
        imgPage: "/img/9.png",
        price: "159000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/9.png"},
            {imgDetail: "/img/9-2.png"},
            {imgDetail: "/img/9-3.png"},
            {imgDetail: "/img/9-4.png"},
            {imgDetail: "/img/9-5.png"},
            {imgDetail: "/img/9-6.png"},
        ],
        itemNumber: "STYLE NO: HQ1474-201",
        color: "COLOR: RED SEPIA/MINK BROWN"
    },
    {
        id:6,
        title: "JORDAN",
        sub_title: "AIR JORDAN 1 RETRO LOW OG",
        content: "에어 조던 1 레트로 로우 OG 옵시디언",
        product_img: "/img/10.png",
        imgPage: "/img/10.png",
        price: "169000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/10.png"},
            {imgDetail: "/img/10-2.png"},
            {imgDetail: "/img/10-3.png"},
            {imgDetail: "/img/10-4.png"},
            {imgDetail: "/img/10-5.png"},
            {imgDetail: "/img/10-6.png"},
            {imgDetail: "/img/10-7.png"},
            {imgDetail: "/img/10-8.png"},
        ],
        itemNumber: "STYLE NO: CZ0790-400",
        color: "COLOR: OBSIDIAN/UNIVERSITY BLUE-SAIL"
    },
    {
        id:7,
        title: "NIKE",
        sub_title: "NIKE SHOX RIDE 2",
        content: "나이키 샥스 라이드 2 블랙 리플렉트 실버",
        product_img: "/img/11.png",
        imgPage: "/img/11.png",
        price: "219000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/11.png"},
            {imgDetail: "/img/11-2.png"},
            {imgDetail: "/img/11-3.png"},
            {imgDetail: "/img/11-4.png"},
            {imgDetail: "/img/11-5.png"},
            {imgDetail: "/img/11-6.png"},
        ],
        itemNumber: "STYLE NO: IB7684-001",
        color: "COLOR: BLACK/SAIL-PHANTOM-REFLECT SILVER"
    },
    {
        id:8,
        title: "ADIDAS",
        sub_title: "SPORTY & RICH X ADIDAS HANDBALL SPEZIAL",
        content: "스포티 앤 리치 X 아디다스 핸드볼 스페지알 나이트 인디고 클라우드 화이트",
        product_img: "/img/12.png",
        imgPage: "/img/12.png",
        price: "135200",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/12.png"},
            {imgDetail: "/img/12-2.png"},
            {imgDetail: "/img/12-3.png"},
            {imgDetail: "/img/12-4.png"},
            {imgDetail: "/img/12-5.png"},
            {imgDetail: "/img/12-6.png"},
        ],
        itemNumber: "STYLE NO: JP7066",
        color: "COLOR: NINDIG/FTWWHT/GUM3"
    },
    {
        id:9, //LAUNCHES 아이템
        title: "JORDAN",
        sub_title: "AIR JORDAN 4 RETRO WMNS",
        content: "에어 조던 4 레트로 우먼스 알루미늄",
        product_img: "/img/19.png",
        imgPage: "/img/19.png",
        price: "259000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/19.png"},
            {imgDetail: "/img/19-2.png"},
            {imgDetail: "/img/19-3.png"},
            {imgDetail: "/img/19-4.png"},
            {imgDetail: "/img/19-5.png"},
            {imgDetail: "/img/19-6.png"},
            {imgDetail: "/img/19-7.png"},
        ],
        itemNumber: "STYLE NO: HV0823-100",
        color: "COLOR: WHITE/ALUMINUM-BLUE TINT-OIL GREEN"
    },
    {
        id:10, //LAUNCHES 아이템
        title: "PUMA",
        sub_title: "ARIES X PUMA MOSTRO MID F&F",
        content: "에리즈 X 푸마 모스트로 미드 F&F 스트롱 그레이 초콜렛",
        product_img: "/img/20.png",
        imgPage: "/img/20.png",
        price: "269000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/20.png"},
            {imgDetail: "/img/20-2.png"},
            {imgDetail: "/img/20-3.png"},
            {imgDetail: "/img/20-4.png"},
            {imgDetail: "/img/20-5.png"},
            {imgDetail: "/img/20-6.png"},
            {imgDetail: "/img/20-7.png"},
        ],
        itemNumber: "STYLE NO: 40119201",
        color: "COLOR: STRONG GRAY-CHOCOLA"
    },
    {
        id:11, //LAUNCHES 아이템
        title: "PUMA",
        sub_title: "ARIES X PUMA MOSTRO CRAFT",
        content: "에리즈 X 푸마 모스트로 크래프트 에크루 마우스 그레이",
        product_img: "/img/21.png",
        imgPage: "/img/21.png",
        price: "239000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/21.png"},
            {imgDetail: "/img/21-2.png"},
            {imgDetail: "/img/21-3.png"},
            {imgDetail: "/img/21-4.png"},
            {imgDetail: "/img/21-5.png"},
        ],
        itemNumber: "STYLE NO: 40131801",
        color: "COLOR: ECRU-MOUSE GRAY"
    },
    {
        id:12, //LAUNCHES 아이템
        title: "PUMA",
        sub_title: "ARIES X PUMA MOSTRO CRAFT",
        content: "에리즈 X 푸마 모스트로 크래프트 마호가니 티크",
        product_img: "/img/22.png",
        imgPage: "/img/22.png",
        price: "239000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/22.png"},
            {imgDetail: "/img/22-2.png"},
            {imgDetail: "/img/22-3.png"},
            {imgDetail: "/img/22-4.png"},
            {imgDetail: "/img/22-5.png"},
        ],
        itemNumber: "STYLE NO: 40131802",
        color: "COLOR: MAHOGANY-TEAK"
    },
    {
        id:13, //Lores 아이템
        title: "LORES",
        sub_title: "LORES Puppet Logo L/S Tee",
        content: "로어즈 퍼핏 로고 긴팔 티셔츠 크림",
        product_img: "/img/28.png",
        imgPage: "/img/28.png",
        price: "44100",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/28.png"},
            {imgDetail: "/img/28-2.png"},
            {imgDetail: "/img/28-3.png"},
            {imgDetail: "/img/28-4.png"},
            {imgDetail: "/img/28-5.png"},
            {imgDetail: "/img/28-6.png"},
            {imgDetail: "/img/28-7.png"},
        ],
        itemNumber: "STYLE NO: LOR25SULS0003CR",
        color: "COLOR: CREAM"
    },
    {
        id:14, //Lores 아이템
        title: "LORES",
        sub_title: "LORES Mesh Zip Hoodie",
        content: "로어즈 메쉬 집 후디 그린",
        product_img: "/img/29.png",
        imgPage: "/img/29.png",
        price: "98100",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/29.png"},
            {imgDetail: "/img/29-2.png"},
            {imgDetail: "/img/29-3.png"},
            {imgDetail: "/img/29-4.png"},
            {imgDetail: "/img/29-5.png"},
            {imgDetail: "/img/29-6.png"},
            {imgDetail: "/img/29-7.png"},
        ],
        itemNumber: "STYLE NO: LOR25SUHD0002GE",
        color: "COLOR: GREEN"
    },
    {
        id:15, //Lores 아이템
        title: "LORES",
        sub_title: "LORES Hooded Waffle L/S Tee",
        content: "로어즈 후디드 와플 긴팔 티셔츠 네이비",
        product_img: "/img/30.png",
        imgPage: "/img/30.png",
        price: "53400",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/30.png"},
            {imgDetail: "/img/30-2.png"},
            {imgDetail: "/img/30-3.png"},
            {imgDetail: "/img/30-4.png"},
            {imgDetail: "/img/30-5.png"},
            {imgDetail: "/img/30-6.png"},
            {imgDetail: "/img/30-7.png"},
        ],
        itemNumber: "STYLE NO: LOR24SUHD0002",
        color: "COLOR: NAVY"
    },
    {
        id:16, //Lores 아이템
        title: "LORES",
        sub_title: "LORES Hooded Waffle L/S Tee",
        content: "로어즈 후디드 와플 긴팔 티셔츠 그레이",
        product_img: "/img/31.png",
        imgPage: "/img/31.png",
        price: "53400",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/31.png"},
            {imgDetail: "/img/31-2.png"},
            {imgDetail: "/img/31-3.png"},
            {imgDetail: "/img/31-4.png"},
            {imgDetail: "/img/31-5.png"},
            {imgDetail: "/img/31-6.png"},
            {imgDetail: "/img/31-7.png"},
        ],
        itemNumber: "STYLE NO: LOR24SUHD0001",
        color: "COLOR: GREY"
    },
    {
        id:17, //Wkndrs 아이템
        title: "WKNDRS",
        sub_title: "WKNDRS APPLIQUE HOODIE",
        content: "위캔더스 아플리케 후디 라이트 그레이",
        product_img: "/img/33.png",
        imgPage: "/img/33.png",
        price: "92650",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/33.png"},
            {imgDetail: "/img/33-2.png"},
            {imgDetail: "/img/33-3.png"},
            {imgDetail: "/img/33-4.png"},
            {imgDetail: "/img/33-5.png"},
            {imgDetail: "/img/33-6.png"},
        ],
        itemNumber: "STYLE NO: WS2503HD01LG",
        color: "COLOR: L.GREY"
    },
    {
        id:18, //Wkndrs 아이템
        title: "WKNDRS",
        sub_title: "WKNDRS SHADOW T-SHIRT",
        content: "위캔더스 섀도우 티셔츠 차콜",
        product_img: "/img/34.png",
        imgPage: "/img/34.png",
        price: "50150",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/34.png"},
            {imgDetail: "/img/34-2.png"},
            {imgDetail: "/img/34-3.png"},
            {imgDetail: "/img/34-4.png"},
            {imgDetail: "/img/34-5.png"},
            {imgDetail: "/img/34-6.png"},
        ],
        itemNumber: "STYLE NO: WS2503TS01CC",
        color: "COLOR: CHARCOAL"
    },
    {
        id:19, //Wkndrs 아이템
        title: "WKNDRS",
        sub_title: "WKNDRS LOVER T-SHIRT",
        content: "위캔더스 러버 티셔츠 화이트",
        product_img: "/img/35.png",
        imgPage: "/img/35.png",
        price: "38250",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/35.png"},
            {imgDetail: "/img/35-2.png"},
            {imgDetail: "/img/35-3.png"},
            {imgDetail: "/img/35-4.png"},
            {imgDetail: "/img/35-5.png"},
            {imgDetail: "/img/35-6.png"},
        ],
        itemNumber: "STYLE NO: WS2503TS03WT",
        color: "COLOR: WHITE"
    },
    {
        id:20, //Wkndrs 아이템
        title: "WKNDRS",
        sub_title: "WKNDRS BASEBALL JERSEY",
        content: "위캔더스 베이스볼 저지 그레이",
        product_img: "/img/36.png",
        imgPage: "/img/36.png",
        price: "101150",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/36.png"},
            {imgDetail: "/img/36-2.png"},
            {imgDetail: "/img/36-3.png"},
            {imgDetail: "/img/36-4.png"},
            {imgDetail: "/img/36-5.png"},
            {imgDetail: "/img/36-6.png"},
            {imgDetail: "/img/36-7.png"},
        ],
        itemNumber: "STYLE NO: WS2503SH01GR",
        color: "COLOR: GREY"
    },
    {
        id:21, //Lockheedmartin 아이템
        title: "LOCKHEEDMARTIN",
        sub_title: "LOCKHEEDMARTIN F35 GARMENT DYED BRUSH T-SHIRT",
        content: "록히드마틴 F35 가먼트 다이드 브러쉬 반팔 티셔츠 블루",
        product_img: "/img/38.png",
        imgPage: "/img/38.png",
        price: "54600",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/38.png"},
            {imgDetail: "/img/38-2.png"},
            {imgDetail: "/img/38-3.png"},
            {imgDetail: "/img/38-4.png"},
            {imgDetail: "/img/38-5.png"},
            {imgDetail: "/img/38-6.png"},
            {imgDetail: "/img/38-7.png"},
            {imgDetail: "/img/38-8.png"},
        ],
        itemNumber: "STYLE NO: L24UTS002BLE",
        color: "COLOR: BLUE"
    },
    {
        id:22, //Lockheedmartin 아이템
        title: "LOCKHEEDMARTIN",
        sub_title: "LOCKHEEDMARTIN MULTI CARGO WOVEN SHORTS",
        content: "록히드마틴 멀티 카고 우븐 쇼츠 카키",
        product_img: "/img/39.png",
        imgPage: "/img/39.png",
        price: "158000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/39.png"},
            {imgDetail: "/img/39-2.png"},
            {imgDetail: "/img/39-3.png"},
            {imgDetail: "/img/39-4.png"},
            {imgDetail: "/img/39-5.png"},
            {imgDetail: "/img/39-6.png"},
        ],
        itemNumber: "STYLE NO: L24UPS002KHA",
        color: "COLOR: KHAKI"
    },
    {
        id:23, //Lockheedmartin 아이템
        title: "LOCKHEEDMARTIN",
        sub_title: "LOCKHEEDMARTIN LM F-35 TEAM REFLECTIVE BLOCKCORE T-SHRIT",
        content: "록히드마틴 LM F-35 팀 리플렉티브 블록코어 반팔 티셔츠 네이비",
        product_img: "/img/40.png",
        imgPage: "/img/40.png",
        price: "47600",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/40.png"},
            {imgDetail: "/img/40-2.png"},
            {imgDetail: "/img/40-3.png"},
            {imgDetail: "/img/40-4.png"},
            {imgDetail: "/img/40-5.png"},
            {imgDetail: "/img/40-6.png"},
            {imgDetail: "/img/40-7.png"},
            {imgDetail: "/img/40-8.png"},
            {imgDetail: "/img/40-9.png"},
        ],
        itemNumber: "STYLE NO: L24UTS003NAV",
        color: "COLOR: NAVY"
    },
    {
        id:24, //Lockheedmartin 아이템
        title: "LOCKHEEDMARTIN",
        sub_title: "LOCKHEEDMARTIN GARMENT DYED CARPENTER SHORTS",
        content: "록히드마틴 가먼트 다이드 카펜터 쇼츠 반바지 차콜",
        product_img: "/img/41.png",
        imgPage: "/img/41.png",
        price: "94800",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/41.png"},
            {imgDetail: "/img/41-2.png"},
            {imgDetail: "/img/41-3.png"},
            {imgDetail: "/img/41-4.png"},
            {imgDetail: "/img/41-5.png"},
            {imgDetail: "/img/41-6.png"},
            {imgDetail: "/img/41-7.png"},
            {imgDetail: "/img/41-8.png"},
        ],
        itemNumber: "STYLE NO: L24UPS001CHA",
        color: "COLOR: CHARCOAL"
    },
    {
        id:25, //Miloarchive 아이템
        title: "MILLO ARCHIVE",
        sub_title: "MILLO ARCHIVE Dainty Curve Detail T-Shirts",
        content: "밀로 아카이브 데인티 커브 디테일 티셔츠 샌드 베이지",
        product_img: "/img/43.png",
        imgPage: "/img/43.png",
        price: "46800",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/43.png"},
            {imgDetail: "/img/43-2.png"},
            {imgDetail: "/img/43-3.png"},
            {imgDetail: "/img/43-4.png"},
            {imgDetail: "/img/43-5.png"},
            {imgDetail: "/img/43-6.png"},
            {imgDetail: "/img/43-7.png"},
        ],
        itemNumber: "STYLE NO: DSSTOML510SBE",
        color: "COLOR: SAND BEIGE"
    },
    {
        id:26, //Miloarchive 아이템
        title: "MILLO ARCHIVE",
        sub_title: "MILLO ARCHIVE Crop Hairy Knit Zip-Up",
        content: "밀로 아카이브 크롭 헤어리 니트 집업 블랙",
        product_img: "/img/44.png",
        imgPage: "/img/44.png",
        price: "86400",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/44.png"},
            {imgDetail: "/img/44-2.png"},
            {imgDetail: "/img/44-3.png"},
            {imgDetail: "/img/44-4.png"},
            {imgDetail: "/img/44-5.png"},
        ],
        itemNumber: "STYLE NO: DPPKNML483BLK",
        color: "COLOR: BLACK"
    },
    {
        id:27, //Miloarchive 아이템
        title: "MILLO ARCHIVE",
        sub_title: "MILLO ARCHIVE Crop Silhouette Knit",
        content: "밀로 아카이브 크롭 실루엣 니트 스모크 블루",
        product_img: "/img/45.png",
        imgPage: "/img/45.png",
        price: "86400",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/45.png"},
            {imgDetail: "/img/45-2.png"},
            {imgDetail: "/img/45-3.png"},
            {imgDetail: "/img/45-4.png"},
            {imgDetail: "/img/45-5.png"},
        ],
        itemNumber: "STYLE NO: CFWKNML425SMB",
        color: "COLOR: Smoke Blue"
    },
    {
        id:28, //Miloarchive 아이템
        title: "MILLO ARCHIVE",
        sub_title: "MILLO ARCHIVE Reflect Curved Pants",
        content: "밀로 아카이브 리플렉트 커브드 팬츠 워시드 카키",
        product_img: "/img/46.png",
        imgPage: "/img/46.png",
        price: "69000",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/46.png"},
            {imgDetail: "/img/46-2.png"},
            {imgDetail: "/img/46-3.png"},
            {imgDetail: "/img/46-4.png"},
            {imgDetail: "/img/46-5.png"},
            {imgDetail: "/img/46-6.png"},

        ],
        itemNumber: "STYLE NO: AFWPTML163WKK",
        color: "COLOR: Washed Khaki"
    },
    {
        id:29, //Americanneedle 아이템
        title: "AMERICAN NEEDLE",
        sub_title: "AMERICAN NEEDLE BALLPARK LOS ANGELES",
        content: "아메리칸 니들 볼파크 로스 엔젤레스 딥 로얄",
        product_img: "/img/48.png",
        imgPage: "/img/48.png",
        price: "25350",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/48.png"},
            {imgDetail: "/img/48-2.png"},
            {imgDetail: "/img/48-3.png"},
            {imgDetail: "/img/48-4.png"},
            {imgDetail: "/img/48-5.png"},
            {imgDetail: "/img/48-6.png"},
            {imgDetail: "/img/48-7.png"},
        ],
        itemNumber: "STYLE NO: SMU674LLOSA",
        color: "COLOR: DEEP ROYAL"
    },
    {
        id:30, //Americanneedle 아이템
        title: "AMERICAN NEEDLE",
        sub_title: "AMERICAN NEEDLE ARCHIVE NEW YORK BLACK YKEES NL",
        content: "아메리칸 니들 아카이브 뉴욕 블랙 YKEES NL 블랙",
        product_img: "/img/49.png",
        imgPage: "/img/49.png",
        price: "29250",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/49.png"},
            {imgDetail: "/img/49-2.png"},
            {imgDetail: "/img/49-3.png"},
            {imgDetail: "/img/49-4.png"},
            {imgDetail: "/img/49-5.png"},
            {imgDetail: "/img/49-6.png"},
            {imgDetail: "/img/49-7.png"},
            {imgDetail: "/img/49-8.png"},
        ],
        itemNumber: "STYLE NO: SMU694BNBY",
        color: "COLOR: BLACK"
    },
    {
        id:31, //Americanneedle 아이템
        title: "AMERICAN NEEDLE",
        sub_title: "AMERICAN NEEDLE BALLPARK IRONSIDE",
        content: "아메리칸 니들 볼파크 아이언사이드 모스",
        product_img: "/img/50.png",
        imgPage: "/img/50.png",
        price: "25350",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/50.png"},
            {imgDetail: "/img/50-2.png"},
            {imgDetail: "/img/50-3.png"},
            {imgDetail: "/img/50-4.png"},
            {imgDetail: "/img/50-5.png"},
            {imgDetail: "/img/50-6.png"},
            {imgDetail: "/img/50-7.png"},
        ],
        itemNumber: "STYLE NO: SMU674BIRONSIDE",
        color: "COLOR: MOSS"
    },
    {
        id:32, //Americanneedle 아이템
        title: "AMERICAN NEEDLE",
        sub_title: "AMERICAN NEEDLE ARCHIVE GIN & TONICE",
        content: "아메리칸 니들 아카이브 진 & 토닉 네이비",
        product_img: "/img/51.png",
        imgPage: "/img/51.png",
        price: "25350",
        membership: "멤버십 혜택 카시나 회원 혜택 확인",
        ImgDetail: [
            {imgDetail: "/img/51.png"},
            {imgDetail: "/img/51-2.png"},
            {imgDetail: "/img/51-3.png"},
            {imgDetail: "/img/51-4.png"},
            {imgDetail: "/img/51-5.png"},
            {imgDetail: "/img/51-6.png"},
            {imgDetail: "/img/51-7.png"},
        ],
        itemNumber: "STYLE NO: SMU714AGINTON",
        color: "COLOR: NAVY"
    },
   ]

export default data;


